worker_processes auto;
error_log /var/log/nginx/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /var/log/nginx/access.log;

    proxy_cache_path /var/cache/nginx/reports levels=1:2 keys_zone=reports_cache:20m max_size=500m inactive=60m use_temp_path=off;

    upstream minio_s3 {
        server minio:9000;
    }

    server {
        listen 80;
        server_name _;

        # Эмуляция CDN: кеш ответов MinIO для статических JSON отчётов
        location /reports/ {
            proxy_cache reports_cache;
            proxy_cache_valid 200 5m;
            proxy_cache_key "$scheme$request_method$host$request_uri";
            add_header X-Cache-Status $upstream_cache_status always;

            proxy_http_version 1.1;
            proxy_set_header Host minio:9000;
            proxy_set_header Connection "";

            rewrite ^/reports/(.*)$ /bionicpro-reports/reports/$1 break;
            proxy_pass http://minio_s3;
        }

        location / {
            return 404;
        }
    }
}
