version: '3.8'

services:
  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend


  api:
    build:
      context: ./api
    ports:
      - "8000:8000"
    environment:
      KEYCLOAK_PUBLIC_KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnDgTbxwTHDrgWTM1RgsF
        LKXTdkbqXarluqW8JATs8YvzfolGcUZY/8K21bFb25klUlAMmsNYfh4KCmAU2Nkq
        CzQrUz7CwyOdnIjgz9MgmStGmGf1yXup8rd7xORySLRV4OIdhsSCtYBpAyZ17QlY
        Cj7P5HvxxYmyLB9zH67W9LPlC9GQY/eJxgHoujvi1Je3wPtdsOO1gNx73hgxvBY3
        JKNDK9TItouv7K5y3rmZy/hnpgFaIuqJA9l8Xf4wmYDy9zRT3XtrRqwBjfdl7Cxe
        0+ewOVx4eJ/MQ2blF1FHq/wMUvCtYflN+brd6O++0Q3GIPJS7cnDszN7C282SrWX
        XQIDAQAB
        -----END PUBLIC KEY-----
    depends_on:
      - keycloak