version: '3.8'
name: bionicpro-platform

include:
  - ./pipeline/docker-compose.yml

services:
  openldap:
    image: osixia/openldap:1.5.0  # Явно фиксируем стабильную версию
    container_name: openldap
    command: --copy-service
    #volumes:
      #- ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom:ro
    environment:
      - LDAP_ORGANISATION=bionicpro
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
    networks:
      - bionicpro-network

  keycloak_db:
    image: postgres:14
    container_name: keycloak_db
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - bionicpro-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak_user -d keycloak_db"]
      interval: 3s
      timeout: 3s
      retries: 5

  keycloak:
    image: quay.io/keycloak/keycloak:21.1
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      KC_HOSTNAME_URL: http://localhost:8080
    command: 
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    networks:
      - bionicpro-network
    depends_on:
      keycloak_db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8000
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend

  bionicpro-auth:
    image: ${DOCKER_REGISTRY-}bionicproauth
    container_name: bionicpro-auth
    user: "0:0" # ДОБАВЬТЕ ЭТУ СТРОКУ (Чтобы сервис отчетов мог читать эти ключи)
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_SERVER__KESTREL__LIMITS__MAXREQUESTHEADERSIZE: 32768
      Keycloak__Authority: "http://localhost:8080/realms/reports-realm"
      Keycloak__MetadataAddress: "http://keycloak:8080/realms/reports-realm/.well-known/openid-configuration"
    volumes:
      - shared-auth-keys:/app/shared-auth-keys
    ports:
      - "7000:8080"
    build:
      context: .
      dockerfile: bionicpro-auth/bionicpro-auth/Dockerfile
    depends_on:
      - keycloak
    networks:
      - bionicpro-network

  bionicpro-reports:
    image: ${DOCKER_REGISTRY-}bionicproreports
    container_name: bionicpro-reports
    user: "0:0" # ДОБАВЬТЕ ЭТУ СТРОКУ (Чтобы сервис отчетов мог читать эти ключи)
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_SERVER__KESTREL__LIMITS__MAXREQUESTHEADERSIZE: 32768
      ConnectionStrings__DefaultConnection: "Host=postgres;Database=airflow;Username=airflow;Password=airflow"
    ports:
      - "7001:8080" # Порт для сервиса отчетов    
    build:
      context: .
      dockerfile: bionicpro-reports/bionicpro-reports/Dockerfile
    volumes:
      - shared-auth-keys:/app/shared-auth-keys # Монтируем ТУ ЖЕ самую папку ключей
    depends_on:
      - postgres 
    networks:
      - bionicpro-network

  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"       # S3 API Эндпоинт
      - "9001:9001"       # Консоль управления (логин: minio_admin / пароль: minio_password)
    environment:
      MINIO_ROOT_USER: minio_admin
      MINIO_ROOT_PASSWORD: minio_password
    command: server /data --console-address ":9001"
    networks:
      - bionicpro-network
    volumes:
      - minio-data:/data

networks:
  bionicpro-network:
    name: bionicpro-network
    driver: bridge

volumes:
  shared-auth-keys:
  minio-data:
