worker_processes 1;

events { worker_connections 1024; }
http
{
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;

    upstream frontend {
        server frontend:3000;
    }

    upstream bionicpro-auth {
        server bionicpro-auth:8080;
    }

    server {
        listen 80;
        listen 444 ssl;
        server_name front.bio-pro.local;
        ssl_certificate /etc/certs/front.bio-pro.local.crt;
        ssl_certificate_key /etc/certs/front.bio-pro.local.key;
        location / {
            proxy_pass http://frontend;
        }
    }

    server {
        listen 80;
        listen 444 ssl;
        server_name api.bio-pro.local;
        ssl_certificate /etc/certs/api.bio-pro.local.crt;
        ssl_certificate_key /etc/certs/api.bio-pro.local.key;
        location / {
            proxy_pass http://bionicpro-auth;
        }
    }

}