worker_processes 1;

events { worker_connections 1024; }
http
{
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;


    server {
        listen 80;
        listen 444 ssl;
        server_name front.bio-pro.local;
        ssl_certificate /etc/certs/front.bio-pro.local.crt;
        ssl_certificate_key /etc/certs/front.bio-pro.local.key;
        location / {
            proxy_pass http://frontend:3000;
        }
    }

    server {
        listen 80;
        listen 444 ssl;
        server_name api.bio-pro.local;
        ssl_certificate /etc/certs/api.bio-pro.local.crt;
        ssl_certificate_key /etc/certs/api.bio-pro.local.key;
              
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        location / {
            proxy_pass http://10.211.55.3:5263;
            proxy_http_version 1.1;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header X-Forwarded-Ssl on;
            proxy_set_header X-Url-Scheme https;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }

    server {
        listen 80;
        listen 444 ssl;
        server_name report.bio-pro.local;
        ssl_certificate /etc/certs/report.bio-pro.local.crt;
        ssl_certificate_key /etc/certs/report.bio-pro.local.key;
              
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;
        location / {
            proxy_pass http://10.211.55.3:5263;
            proxy_http_version 1.1;
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_set_header X-Forwarded-Ssl on;
            proxy_set_header X-Url-Scheme https;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }


    server {
        listen 443 ssl;
        server_name key.bio-pro.local;

        ssl_certificate /etc/certs/key.bio-pro.local.crt;
        ssl_certificate_key /etc/certs/key.bio-pro.local.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        location / {
            proxy_pass http://keycloak:8080;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Port 443;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }



}