worker_processes  1;

events {
  worker_connections  1024;
}

http {
  proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=reports_cache:10m
                   max_size=1g inactive=24h use_temp_path=off;

  upstream minio_s3 {
    server minio:9090;
  }

  server {
    listen 80;
    server_name _;

    location /reports/ {
      proxy_pass http://minio_s3/static$uri;

      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;

      proxy_hide_header Access-Control-Allow-Origin;
      proxy_hide_header Access-Control-Allow-Methods;
      proxy_hide_header Access-Control-Allow-Headers;
      proxy_hide_header Access-Control-Allow-Credentials;

      add_header Access-Control-Allow-Origin http://localhost:3000 always;
      add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
      add_header Access-Control-Allow-Headers "Content-Type, Accept" always;
      add_header Access-Control-Allow-Credentials "true" always;

      if ($request_method = OPTIONS) {
          return 204;
      }

      proxy_cache reports_cache;
      proxy_cache_valid 200 24h;
      proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
      add_header X-Cache-Status $upstream_cache_status;
    }
  }
}
